增加 kqueue.c 注释
CN-annotation-team/redis7.0-chinese-annotated pull request #101
Opened 2023-01-06 12:43 UTC by ysdlb

#99 [新注释] ae_kqueue.c

2023-01-07 09:15 UTC, enjoy-binbin requested changes
thanks for the update, added some suggestions for the modification

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + * https://www.freebsd.org/cgi/man.cgi?query=kevent&apropos=0&sektion=0&manpath=FreeBSD+6.1-RELEASE&format=html
```suggestion
/* kqueue 是一个可扩展的事件通知接口，在 OS X、FreeBSD 中均有其实现，在这里作为 redis polling api 的实现方式之一
 * 同 evport 和 epoll，事件(描述符)提取的算法复杂度为 O(1)，支持超过 1024 个文件描述符
 *
 * kqueue api 在 redis 下的使用场景:
 *
 * int kqueue(void);
 *   创建一个新的内核事件队列，返回一个描述符 (kqfd)
 *
 * int kevent(int kq, const struct kevent *changelist, int nchanges, struct kevent *eventlist, int nevents, const struct timespec *timeout);
 *   1. 注册/删除新的可读/可写事件
 *   2. 获取已触发事件，需要注意的是，对同一个 fd 的不同事件 (比如读和写)，kqueue 实现会分多个不同的就绪事件给到
 *
 * EV_SET(_kev, ident, filter, flags, fflags, data, udata);
 *   初始化 struct kevent 对象的宏
 *
 * 以上仅是 redis 使用到的功能，相关 api 的详细介绍见:
 * https://www.freebsd.org/cgi/man.cgi?query=kevent&apropos=0&sektion=0&manpath=FreeBSD+6.1-RELEASE&format=html
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + */
```suggestion
/* kqueue 的私有数据
 *     kqfd: 系统调用 kqueue() 分配的 kqueue 队列文件描述符，后续都基于这个 kqfd 来 注册/注销 事件监听
 *     events: kevent() 系统调用返回的已触发事件，这里是数组首元素的指针，数组会初始化 setsize 个位置
 *     eventsMasks: char 数组，其 size 和 数组 events 的长度相关
 *         数组 events 中的每个 event，都有可读/可写两个独立状态，一个掩码需要 2bits 来存储
 *         因此一个 8bits 的 char 字符可以存储 4 个 event 的掩码
 *         两个数组的长度关系为 len(eventsMasks) = (len(events) + 3) / 4，见宏定义: EVENT_MASK_MALLOC_SIZE
 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + * 计算过程: 先获取掩码所在的 char 字符, 然后将其移位到最后两位 */
```suggestion
 * 计算过程：先获取掩码所在的 char 字符，然后将其移位到最后两位 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +/* 复位 fd 对应的掩码, 将掩码的 2 bits 设置为 0 */
```suggestion
/* 复位 fd 对应的掩码，将掩码的 2 bits 设置为 0 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + * 最后将 kqueue 的 aeApiState 私有数据保存在全局变量 aeEventLoop.apidata 中
```suggestion
/* 创建 kqueue 多路复用库的私有数据
 *     1. 创建 kqueue event 数组 (state->events)，掩码数组 (state->eventsMask)
 *     2. 创建 kqueue 队列，得到文件描述符 kqfd
 * 最后将 kqueue 的 aeApiState 私有数据保存在全局变量 aeEventLoop.apidata 中
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +    /* 避免 fd 泄漏, 设置 kqueue fd 运行时可关闭 */
```suggestion
    /* 避免 fd 泄漏，设置 kqueue fd 运行时可关闭 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + * Question: 为什么需要将数组 state->eventsMask 重新设置为 0 */
> Question: 为什么需要将数组 state->eventsMask 重新设置为 0

这边我猜，本身 resize 的话，就需要说对这些掩码重新初始化置0，无论是往大的 resize 还是往小的 resize，然后这个置 0 其实应该也不咋影响，因为在 aeApiPoll 里每次对事件处理的时候，都会重新计算每个事件的 mask 然后进行赋值

```suggestion
/* 按照给定的 setsieze，重新分配 kqueue event 数组和相对应掩码数组的大小 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + *   mask: 标记监听事件类型, 读事件(AE_READABLE) or 写事件(AE_WRITABLE) */
```suggestion
 *   mask: 标记监听事件类型，读事件(AE_READABLE) or 写事件(AE_WRITABLE) */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +/* 删除事件, 将宏定义 EV_SET 的 EV_ADD 参数替换为 EV_DELETE, 其他同 aeApiAddEvent 函数 */
```suggestion
/* 删除事件，将宏定义 EV_SET 的 EV_ADD 参数替换为 EV_DELETE，其他同 aeApiAddEvent 函数 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> + * return: 就绪事件涉及到的 fd 数量 */
```suggestion
/* 获取就绪事件，并将 kqueue 事件数据转化为 redis 事件数据
 * return: 就绪事件涉及到的 fd 数量 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +        /* 设置阻塞(超时)时间, 若该值为 NULL, 则无限期阻塞, 直到有事件触发 */
```suggestion
        /* 设置阻塞(超时)时间，若该值为 NULL，则无限期阻塞，直到有事件触发 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +        /* 至多获取 setsize 个就绪事件, 将就绪事件放在 kqueue 私有的数组 events 中, 返回获取的就绪事件数量; 若无就绪事件, 超时返回 0 */
```suggestion
        /* 至多获取 setsize 个就绪事件，将就绪事件放在 kqueue 私有的数组 events 中，返回获取的就绪事件数量；若无就绪事件，超时返回 0 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +        /* 第一次遍历就绪事件, 目的: kqueue 同 fd 的可读事件和可写事件, 需要用两个就绪事件来表示, 这里的目的是将事件的状态合并 */
```suggestion
        /* 第一次遍历就绪事件，目的：kqueue 同一个 fd 的可读事件和可写事件，kqueue 中会用两个就绪事件来表示，这里的目的是将事件的状态合并
        * 例如将 kqueue 返回的 fd 可读和 fd 可写事件，合并表示成一个 fd 可读可写，不然的话无法控制 kqueue 中事件读写的顺序 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +        /* fd 掩码合并后的第二次遍历, numevents 表示存在就绪事件的 fd 的数量, 不是就绪事件的数量 */
```suggestion
        /* fd 掩码合并后的第二次遍历，numevents 表示存在就绪事件的 fd 的数量，而不是就绪事件的数量 */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +             *      若 fd 有多个就绪事件, 后续事件的 mask == 0, 将不会走下面逻辑, 保证了 numevents 对同 fd 的多个事件, 只会计数一次. */
```suggestion
            /* 1. 若为可读/可写，将 kqueue 私有数据转化为 eventLoop 数据
             * 2. 复位私有的掩码值:
             *      若一个 fd 有多个就绪事件，后续事件在遍历的时候，mask == 0，将不会走下面逻辑，保证了 numevents 对同 fd 的多个事件，只会计数一次. */
```

2023-01-07 09:15 UTC, enjoy-binbin commented on src/ae_kqueue.c
> +/* 返回改 polling api 实现的名字 */
```suggestion
/* 返回该 polling api 实现的名字 */
```

2023-01-08 03:42 UTC, ysdlb commented on src/ae_kqueue.c
> + * Question: 为什么需要将数组 state->eventsMask 重新设置为 0 */
看了下代码，确实是每次 eventLoop 都会重新取事件并计算 mask 的值，谢谢解答

2023-01-08 05:56 UTC, enjoy-binbin approved these changes

2023-01-08 05:58 UTC, merged