增加整数集合的部分注释 intset.c
CN-annotation-team/redis7.0-chinese-annotated pull request #12
Opened 2022-05-02 14:48 UTC by Super-ZZGuo

intset还有部分注释未完成的

2022-05-02 14:52 UTC, ncghost1 requested changes

2022-05-02 14:52 UTC, ncghost1 commented on src/intset.c
> +     * 例如:encoding 选项为 INTSET_ENC_INT16时, 数组里的每个项都为一个int16_t类型的整数值(-32768——32767)*/
注意格式，英文和中文之间要有空格

2022-05-03 05:52 UTC, ncghost1 commented on src/intset.c
> +/* 将整数集合升级为更大的编码 并插入给定的整数 */
“更大的编码”意思不够准确，再改改

2022-05-03 05:52 UTC, ncghost1 commented on README.md
> +| intset.ch |  整数集合数据结构的相关声明 | 完成 |
.h，错别字

2022-05-03 05:53 UTC, Super-ZZGuo commented on README.md
> +| intset.ch |  整数集合数据结构的相关声明 | 完成 |
好的

2022-05-03 06:01 UTC, ncghost1 commented on src/intset.c
> + * 编码升级： 例如由 INTSET_ENC_INT16 升级为 INTSET_ENC_INT16 */
呃……名称重复了

2022-05-03 06:01 UTC, Super-ZZGuo commented on src/intset.c
> +/* 将整数集合升级为更大的编码 并插入给定的整数 */
已修改

2022-05-03 06:03 UTC, Super-ZZGuo commented on src/intset.c
> + * 编码升级： 例如由 INTSET_ENC_INT16 升级为 INTSET_ENC_INT16 */
。。。已修改😭

2022-05-03 06:03 UTC, ncghost1 approved these changes

2022-05-03 06:03 UTC, merged

2022-05-03 06:04 UTC, ncghost1 commented
感谢贡献的注释！
然后由于您贡献的注释超过了50行，我们接下来会给您发送加入咱们“小组织”的邀请，请留意～