feat： cluster.h文件添加注释
CN-annotation-team/redis7.0-chinese-annotated pull request #55
Opened 2022-09-08 06:59 UTC by huihuang-chen

2022-09-08 07:04 UTC, ncghost1 commented on src/cluster.h
> +/* 集群挂了 */
```suggestion
/* 集群失效 */
```

2022-09-08 07:04 UTC, ncghost1 commented on src/cluster.h
> +/* 撤销主节点FAIL状态的乘法因子 */
```suggestion
/* 撤销主节点 FAIL 状态的乘法因子 */
```
扫了一眼下边还有很多英文和中文之间没有空格的，需要加上空格来符合注释格式要求。

2022-09-08 07:44 UTC, huihuang-chen reviewed
cluster.h添加中文注释

2022-09-08 08:07 UTC, huihuang-chen commented on src/cluster.h
> +/* 撤销主节点FAIL状态的乘法因子 */
请问一下这个注释审核容易过吗

2022-09-08 13:54 UTC, ncghost1 commented on src/cluster.h
> +/* 撤销主节点FAIL状态的乘法因子 */
不会过不了的，只是可能有问题或者有要补充的会让你或者我们自己修改，然后你这个注释比较多所以可能会看得慢一点（主要是最近我也有别的事要做）

2022-09-09 01:18 UTC, huihuang-chen commented on src/cluster.h
> +/* 撤销主节点FAIL状态的乘法因子 */
好的

2022-09-12 02:39 UTC, enjoy-binbin reviewed
mostly LGTM, thanks for the comments, minor change request.

PS. 大概过了一遍，应该都是对的（我也没有费心思把全部代码都看过，每个东西都看懂 :) ）

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> +/* 有资格做副本漂移的主节点 */
```suggestion
/* 有资格做副本迁移的主节点 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> +/* 集群实际通信的端口 = 用户指定端口 + CLUSTER_PORT_INCR （6379 + 10000 = 16379）*/
```suggestion
/* 默认情况下：集群实际通信的端口 = 用户指定端口 + CLUSTER_PORT_INCR（例如 6379 + 10000 = 16379）
 * 7.0 后也可通过 redis.conf 里的 cluster-port 参数指定 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> + * 最后一种是包类型计数边界，代码中做判断
```suggestion
 * 最后一个 CLUSTERMSG_TYPE_COUNT 是包类型计数边界，代码中做判断
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> + * 其他类型的包都由包头和包体两部分组成，包头格式相同，包体内容更具具体的类型填充 */
```suggestion
 * 其他类型的包都由包头和包体两部分组成，包头格式相同，包体内容根据具体的类型填充 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> +#define CLUSTERMSG_TYPE_FAILOVER_AUTH_REQUEST 5 /* May I failover? failover 授权请求包 */
这里我们都新开行来做注释，我一般想着会少一点变更
```suggestion
/* failover 授权请求包 */
#define CLUSTERMSG_TYPE_FAILOVER_AUTH_REQUEST 5 /* May I failover? */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> +#define CLUSTERMSG_TYPE_FAILOVER_AUTH_ACK 6     /* Yes, you have my vote  （failover 授权确认包） */
/* failover 授权确认包 */
```suggestion
#define CLUSTERMSG_TYPE_FAILOVER_AUTH_ACK 6     /* Yes, you have my vote */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> +#define CLUSTERMSG_TYPE_MFSTART 8       /* Pause clients for manual failover 手动故障转移包 */
```suggestion
/* failover 授权确认包 */
#define CLUSTERMSG_TYPE_MFSTART 8       /* Pause clients for manual failover */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/cluster.h
> + * meet 包：当执行 cluster meet ip port 命令之后，执行端会向 ip:port 指定的地址发送 meet 包，连接建立之后，会定期发送 ping 包 */
```suggestion
 * meet 包：当执行 cluster meet ip port [cluster_bus_port] 命令之后，执行端会向 ip:port 指定的地址发送 meet 包，连接建立之后，会定期发送 ping 包 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/rio.c
> +        /* 四个方法 */
```suggestion
    /* 四个方法 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/rio.c
> +     * */
```suggestion
    /* 增量写数据到文件中，避免单次写的数据量大于 autosync 的阈值
     * 注：为了避免内核缓冲区一次出现太多的脏页 */
```

2022-09-12 02:39 UTC, enjoy-binbin commented on src/rio.c
> +        /* file rio 的四个操作函数*/
```suggestion
    /* file rio 的四个操作函数*/
```

2022-09-12 03:16 UTC, huihuang-chen commented
请问一下，你们提出的这些问题是不是我自己改好再提交

2022-09-12 03:22 UTC, enjoy-binbin commented
是的，你可以在页面上采纳建议
<img width="760" alt="image" src="https://user-images.githubusercontent.com/22811481/189568074-ca0a98a6-2180-45a7-8b40-0be06f3d8c90.png">


也可以自己本地里修改后提交

2022-09-12 03:23 UTC, huihuang-chen commented
好的，谢谢

2022-09-12 07:55 UTC, ncghost1 commented
把 README 的项目进度修改一下谢谢~

2022-09-13 02:22 UTC, ncghost1 commented on README.md
>  更新日期：2022/8/10
```suggestion
更新日期：2022/9/13
```

2022-09-13 02:28 UTC, ncghost1 commented on src/rio.c
> +    /* RIO 中 connection 的 buf 从 pos 位置读 len 个数据到给定的 buf中  */
```suggestion
    /* RIO 中 connection 的 buf 从 pos 位置读 len 个数据到给定的 buf 中  */
```

2022-09-13 02:28 UTC, ncghost1 commented on src/rio.c
> +/* flush 调用器write */
```suggestion
/* flush 调用器 write */
```

2022-09-13 02:28 UTC, ncghost1 commented on src/rio.h
> + * 3. connection (目前只有 RDB 将主节点的rdb文件加载到从服务器内存使用了这种 IO ,只提供读操作)
```suggestion
 * 3. connection (目前只有 RDB 将主节点的 rdb 文件加载到从服务器内存使用了这种 IO ,只提供读操作)
```

2022-09-13 02:28 UTC, ncghost1 commented on src/rio.h
> +/* 这里抽取了 rio 的 read / write /tell 等操作的公共逻辑，会根据不同 rio 类型执行具体的函数 */
```suggestion
/* 这里抽取了 rio 的 read / write / tell 等操作的公共逻辑，会根据不同 rio 类型执行具体的函数 */
```

2022-09-13 02:28 UTC, ncghost1 commented on src/cluster.h
> +    /* 节点名，有大小限制 40个字符 */
```suggestion
    /* 节点名，有大小限制40个字符 */
```

2022-09-13 02:28 UTC, ncghost1 commented on src/cluster.h
> +/* publish 包用来广播publish信息 */
```suggestion
/* publish 包用来广播 publish 信息 */
```

2022-09-13 02:32 UTC, ncghost1 approved these changes
感谢！还有什么要修改或者补充的吗？没有的话就Merge了

2022-09-13 02:37 UTC, huihuang-chen commented
好的，目前没有，之后有在提交

2022-09-13 02:40 UTC, ncghost1 requested changes

2022-09-13 02:40 UTC, ncghost1 commented on src/replication.c
> +            /* 这里又做了一次前移，没看明白？求大佬指教 */
@enjoy-binbin 大佬帮帮叭~

2022-09-14 07:33 UTC, enjoy-binbin commented
抱歉，最近工作上有忙一个新项目，所以没有很多时间，然后你又比较高产哈哈哈，就东西略多然后没有很多时间看

你那边有办法说把 PR 给拆小吗，例如一个 PR 就对一个文件做注释，这样子后面 review 也会方便点，可以把小文件注释的小 PR 给先合并了，看过的部分就不用说被新的内容给 block 住

当然我后面会找时间来 review 的，都有大概过了下，都很好，不过有些内容我自己因为时间久远有点忘记或者有些内容我也没有了解过，所以时间会拖慢一点

2022-09-14 08:13 UTC, huihuang-chen commented
不好意思，第一次玩PR，不太熟悉操作，我先把这个PR关掉，下次提交新的PR

2022-09-14 08:14 UTC, closed without merging